export const Secret_api_key = "https://job-portal-frontend-phi-six.vercel.app"
export const Secret_admin_keys = "https://job-portal-frontend-phi-six.vercel.app/company/"
export const Secret_admin_Jobs_keys = "https://job-portal-frontend-phi-six.vercel.app/job/"
export const Secret_admin_posts_keys = "https://job-portal-frontend-phi-six.vercel.app/post"
export const Secret_admin_application_key="https://job-portal-frontend-phi-six.vercel.app/application"
